#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_TIMEHANDLER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_TIMEHANDLER_HPP


namespace lib {
    class TimeHandler {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_TIMEHANDLER_HPP