#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_VEHICLECONTROLLER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_VEHICLECONTROLLER_HPP


namespace lib {
    class VehicleController {
    };
}


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_VEHICLECONTROLLER_HPP