#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_NETWORKHANDLER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_NETWORKHANDLER_HPP


namespace lib {
    class NetworkHandler {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_NETWORKHANDLER_HPP