#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_FLAPPYBIRDGAME_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_FLAPPYBIRDGAME_HPP


namespace lib {
    class FlappyBirdGame {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_FLAPPYBIRDGAME_HPP