#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_AMBIENT_SENSOR_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_AMBIENT_SENSOR_HPP


namespace lib {
    class AmbientSensor {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_AMBIENT_SENSOR_HPP