#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ULTRASONIC_SENSOR_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ULTRASONIC_SENSOR_HPP


namespace lib {
    float getDistance();
}


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ULTRASONIC_SENSOR_HPP