#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_DISPLAY_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_DISPLAY_HPP


namespace lib {
    class Display {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_DISPLAY_HPP