#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_LIGHTING_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_LIGHTING_HPP


namespace lib {
    class Lighting {
    };
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_LIGHTING_HPP