#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ENVIRONMENT_VARIABLES_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ENVIRONMENT_VARIABLES_HPP

// auto SSID = "Arne";
// auto PASSWORD = "Arne666!";
auto SSID = "";
auto PASSWORD = "";

float latitude = 0.0;
float longitude = 0.0;

#endif  // NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_ENVIRONMENT_VARIABLES_HPP
