#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP
#include <cstdint>

// TODO: Set correct pins

constexpr uint8_t ULTRASONIC_SENSOR_TRIGGER_PIN = -1;
constexpr uint8_t ULTRASONIC_SENSOR_ECHO_PIN = -1;

#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP