#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP
#include <cstdint>

// TODO: Set correct pins

// Pins:
#define ULTRASONIC_SENSOR_TRIGGER_PIN 33
#define ULTRASONIC_SENSOR_ECHO_PIN 34

#define MOTOR_FORWARD_PIN 17
#define MOTOR_REVERSE_PIN 18

#define SERVO_STEERING_PIN 16

#define SPEAKER_AMPLIFIER_LRC 14
#define SPEAKER_AMPLIFIER_BCLK 12
#define SPEAKER_AMPLIFIER_DIN 26

// Ledc Channels:
#define SERVO_STEERING_CHANEL 0

#endif // NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINS_HPP