#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PROJECTTYPES_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PROJECTTYPES_HPP

#include <Arduino.h>



#endif  // NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PROJECTTYPES_HPP
