#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_SPEAKER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_SPEAKER_HPP


namespace lib {
    class Speaker {
    };
}


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_SPEAKER_HPP