#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP


namespace lib {
    void setPinModes();
} // lib


#endif //NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP