#ifndef NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP
#define NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP

namespace pinmode_setter {
void setPinModes();
} // namespace pinmode_setter

#endif // NEXT_GENERATION_SMART_WAKE_UP_DEIVCE_PINMODESETTER_HPP